### ISSUE TITLE
Doesn't work with Newtonsoft.Json 11.0.1

### ISSUE THREAD

**Issue by michalkovy** [fsprojects/SwaggerProvider#107]
When I update my application that uses SwaggerProvider to use Newtonsoft.Json 11.0.1 then the SwaggerProvider will stop working, compilation fails on:
 error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

The update of Newtonsoft.Json happens automatically when I run Paket update. So, at least pnuget package should be made in a way that paket update won't update Newtonsoft.Json in my application. Better solution would be to make SwaggerProvider able to work with any newer Newtonsoft.Json.

**Comment by sergey-tihon** [comment]
Thank you for reporting this @michalkovy. Do you latest stable version or beta?

As workaround, you can pin version in `paket.dependency` like `~>10.0.0`

We do have this issues because we have [custom assembly resolution code](https://github.com/fsprojects/SwaggerProvider/blob/master/src/SwaggerProvider.DesignTime/Configuration.fs) in TP that does not support this case.

I would prefer to take some time to think about the best solution, maybe we could you use target assembly list to resolve design time dependencies ...

**Comment by michalkovy** [comment]
We use SwaggerProvider stable (0.8.2), also Newtonsoft.Json stable. The problem is that 0.8.2 SwaggerProvider nugget package tells that it depends on "Newtonsoft.Json (>= 10.0.0)",  I see that you fixed that in beta of SwaggerProvider nugget package as it depends on "Newtonsoft.Json (>= 10.0.3 && < 10.1.0)". Thanks for workaround provided.

**Comment by sergey-tihon** [comment]
[SwaggerProvider 0.10.0-beta09](https://www.nuget.org/packages/SwaggerProvider/0.10.0-beta09) should be good with latest Newtonsoft.Json
